# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ad75d468-8073-4101-9123-4353f0a38818";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DC23-39A8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/external/l" =
    { device = "/dev/disk/by-uuid/CA084DA8084D947B";
      fsType = "ntfs-3g";
      options = [ "rwx" "uid=1000" "gid=100" ];
    };
 
  fileSystems."/external/s" =
    { device = "/dev/disk/by-uuid/9E2A72262A71FB99";
      fsType = "ntfs-3g";
      options = [ "rwx" "uid=1000" "gid=100" ];
    };

  fileSystems."/home/simonkdev/k1nas/Fotos" = {
    device = "//192.168.2.138/Public/02_SKP";
    fsType = "cifs";
    options = [
      "credentials=/home/simonkdev/.smbcredentials"
      "uid=1000"
      "gid=100"
      "vers=3.0"
      "iocharset=utf8"
      "nofail"
      "_netdev"
    ];
  };

  fileSystems."/home/simonkdev/k1nas/Obsidian" = {
    device = "//192.168.2.138/Public/Simon_Obsidian";
    fsType = "cifs";
    options = [
      "credentials=/home/simonkdev/.smbcredentials"
      "uid=1000"
      "gid=100"
      "vers=3.0"
      "iocharset=utf8"
      "nofail"
      "_netdev"
    ];
  };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/67025277-dc72-435f-b315-8ce5923913af"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
